import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dutch</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Your Dash</h1>
        <div className={styles.grid}>
          <a className={styles.card} href="/trips">
            <h2>🚌 See Your Trips &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a className={styles.card} href="/createTrip">
            <h2>✨ Create a Trip &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
