import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAccount } from "wagmi";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { address, isConnecting, isDisconnected } = useAccount();
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Dutch</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Dutch</h1>
        <ConnectButton />
        {address && (
          <button onClick={() => router.push("/createTrip")}>
            Create Trip
          </button>
        )}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
