import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAccount } from "wagmi";
import { useRouter } from "next/router";
import { MetaMaskSDK } from "@metamask/sdk";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { address, isConnecting, isDisconnected } = useAccount();
  const router = useRouter();
  const options = {
    dappMetadata: {
      name: "Dutch",
      website: "https://dutch-git-main-dutch-waterloo.vercel.app/",
    },
  };

  const MMSDK = new MetaMaskSDK(options);
  const ethereum = MMSDK.getProvider();
  const connected = ethereum?.isConnected();

  useEffect(() => {}, [connected]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Dutch</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        {connected && (
          <button onClick={() => router.push("/createTrip")}>
            Create Trip
          </button>
        )}
        <h2 className={styles.title}>Split Expenses. Preserve Friendships.</h2>
        <h3>Going Dutch the Socially Acceptable Way.</h3>
        <button
          className={styles.ctaButton}
          onClick={() => router.push("/dash")}
        >
          Sign Up
        </button>
      </main>
    </div>
  );
};

export default Home;
